### ISSUE TITLE
domain() method assumes only the US data centre is used

### ISSUE THREAD

**Issue by johnrhunt** [RiskioFr/oauth2-auth0#7]
Line 22 src/Auth0.php:

```return 'https://' . $this->account . '.auth0.com';```

Ideally a required data centre param needs to be checked for when the class is constructed. We're using the EU data centre at the moment and currently it's impossible to use with this package.

**Comment by johnrhunt** [comment]
As an aside - probably shouldn't have string literals in methods.

**Comment by neeckeloo** [comment]
@johnrhunt What do you think about this pull request #8 ?

**Comment by johnrhunt** [comment]
Hi @neeckeloo - thank you so much for doing this PR, I really appreciate it. I'm about to go on holiday so don't have time to review the PR at the moment, but I will do as soon as I'm back on the 28th - I'm setting a reminder now. 👍

**Comment by neeckeloo** [comment]
@johnrhunt Did you have any time to take a look at this?
